# Configuración general de la aplicación
spring.application.name=tp1-ej6-ind
server.port=8880

# Configuración de conexión a PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/tp1-ej6-ind
spring.datasource.username=postgres
spring.datasource.password=12345
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Thymeleaf
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# Seguridad y auditoría
spring.security.user.name=admin
spring.security.user.password=admin

# SMTP (configura tus credenciales reales si deseas enviar correos reales)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=tu-correo@gmail.com
spring.mail.password=tu-password-app
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com

# Logging
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.springframework.security=DEBUG

