services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: club_deportivo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - club-db:/var/lib/postgresql/data
volumes:
  club-db:
